name: Run Daily Scraper

on:
  schedule:
    - cron: '0 12 * * 1-5'  # Runs at 5 PM PKT (12 PM UTC) Monday–Friday
  workflow_dispatch:

permissions:
  contents: write  # ✅ Allow workflow to push updates

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install openpyxl  # ✅ Ensure Excel writing support

      - name: Run scraper
        run: python scraper.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push updated Excel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add PSX_DailyActivity.xlsx || echo "No file to add"
          git commit -m "Auto update: PSX data $(date)" || echo "Nothing to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
