name: Run Daily Scraper

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 5 PM PKT = 12 PM UTC (Monday–Friday)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updated Excel
        run: |
          git config --global user.name "AhmedRaza-Automation"
          git config --global user.email "ahmedraza@example.com"
          git add PSX_DailyActivity.xlsx || echo "No file to add"
          git commit -m "Auto update: PSX data $(date)" || echo "Nothing to commit"
          git push
